import { test, expect } from "@playwright/test";
import { en } from "../../src/i18n/en";

test.describe("Ticket Status Change", () => {
  test.beforeEach(async ({ page }) => {
    await page.goto("/api/auth/login");
    await page.waitForURL("/");
  });

  test("change ticket status from detail page", async ({
    page,
    request,
  }) => {
    // Create a ticket
    const createRes = await request.post(
      "/api/v1/ws/support/tickets",
      {
        data: { title: "Status Change Test" },
      },
    );
    expect(createRes.status()).toBe(201);
    const ticket = await createRes.json();

    // Default status should be "open"
    expect(ticket.statusId).toBe("open");

    // Go to detail page
    await page.goto(`/ws/support/tickets/${ticket.id}`);
    await expect(page.getByText("Status Change Test")).toBeVisible();

    // Status dropdown trigger should display the current status "Open"
    const statusTrigger = page.getByRole("button", { name: /Open/ });
    await expect(statusTrigger).toBeVisible();

    // Open the status dropdown
    await statusTrigger.click();

    // Click "In Progress" option in the dropdown
    await page.getByRole("button", { name: /In Progress/ }).click();

    // The dropdown trigger should now display "In Progress"
    await expect(
      page.getByRole("button", { name: /In Progress/ }),
    ).toBeVisible();

    // Verify via API
    const getRes = await request.get(
      `/api/v1/ws/support/tickets/${ticket.id}`,
    );
    const updated = await getRes.json();
    expect(updated.statusId).toBe("in-progress");
  });

  // Conclusion section: only editable when status is closed; the LLM
  // close-time autogeneration path is wired through the same usecase, but
  // E2E uses a dummy LLM key so the autogenerated conclusion is empty —
  // the editor still lets the user fill it in manually below.
  test("conclusion is locked while ticket is open", async ({
    page,
    request,
  }) => {
    const created = await request.post("/api/v1/ws/support/tickets", {
      data: { title: "Locked-while-open ticket" },
    });
    expect(created.status()).toBe(201);
    const ticket = await created.json();

    await page.goto(`/ws/support/tickets/${ticket.id}`);
    await expect(page.getByText("Locked-while-open ticket")).toBeVisible();

    await expect(
      page.getByRole("heading", {
        name: en.ticketDetailConclusionLabel,
        exact: true,
      }),
    ).toBeVisible();
    await expect(
      page.getByText(en.ticketDetailConclusionEditLockedHint),
    ).toBeVisible();
    await expect(
      page.getByText(en.ticketDetailConclusionEmpty),
    ).toBeVisible();
  });

  test("conclusion is editable once the ticket is closed", async ({
    page,
    request,
  }) => {
    const created = await request.post("/api/v1/ws/support/tickets", {
      data: { title: "Editable-when-closed ticket" },
    });
    expect(created.status()).toBe(201);
    const ticket = await created.json();

    const close = await request.patch(
      `/api/v1/ws/support/tickets/${ticket.id}`,
      { data: { statusId: "closed" } },
    );
    expect(close.status()).toBe(200);

    await page.goto(`/ws/support/tickets/${ticket.id}`);
    await expect(page.getByText("Editable-when-closed ticket")).toBeVisible();

    const heading = page.getByRole("heading", {
      name: en.ticketDetailConclusionLabel,
      exact: true,
    });
    const conclusionSection = heading.locator("..").locator("..");

    await conclusionSection
      .getByRole("button", { name: en.ticketDetailEdit })
      .click();

    const textarea = conclusionSection.getByRole("textbox");
    await textarea.fill("Manually authored conclusion via E2E.");
    await page
      .getByRole("button", { name: en.ticketDetailSaveChanges })
      .click();

    await expect(
      page.getByText("Manually authored conclusion via E2E."),
    ).toBeVisible();

    const verify = await request.get(
      `/api/v1/ws/support/tickets/${ticket.id}`,
    );
    const stored = await verify.json();
    expect(stored.conclusion).toBe("Manually authored conclusion via E2E.");
  });
});
