// Package http provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package http

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/m-mizutani/shepherd/pkg/domain/types"
	"github.com/oapi-codegen/runtime"
)

// Defines values for FieldType.
const (
	Date        FieldType = "date"
	MultiSelect FieldType = "multi-select"
	Number      FieldType = "number"
	Select      FieldType = "select"
	Text        FieldType = "text"
	Url         FieldType = "url"
	User        FieldType = "user"
)

// Valid indicates whether the value is a known member of the FieldType enum.
func (e FieldType) Valid() bool {
	switch e {
	case Date:
		return true
	case MultiSelect:
		return true
	case Number:
		return true
	case Select:
		return true
	case Text:
		return true
	case Url:
		return true
	case User:
		return true
	default:
		return false
	}
}

// Comment defines model for Comment.
type Comment struct {
	Body        string    `json:"body"`
	CreatedAt   time.Time `json:"createdAt"`
	Id          string    `json:"id"`
	SlackUserId string    `json:"slackUserId"`
}

// CreateTicketRequest defines model for CreateTicketRequest.
type CreateTicketRequest struct {
	AssigneeId  *string       `json:"assigneeId,omitempty"`
	Description *string       `json:"description,omitempty"`
	Fields      *[]FieldValue `json:"fields,omitempty"`
	StatusId    *string       `json:"statusId,omitempty"`
	Title       string        `json:"title"`
}

// EntityLabels defines model for EntityLabels.
type EntityLabels struct {
	Description string `json:"description"`
	Ticket      string `json:"ticket"`
	Title       string `json:"title"`
}

// FieldDefinition defines model for FieldDefinition.
type FieldDefinition struct {
	Description *string        `json:"description,omitempty"`
	Id          string         `json:"id"`
	Name        string         `json:"name"`
	Options     *[]FieldOption `json:"options,omitempty"`
	Required    bool           `json:"required"`
	Type        FieldType      `json:"type"`
}

// FieldOption defines model for FieldOption.
type FieldOption struct {
	Color    *string                 `json:"color,omitempty"`
	Id       string                  `json:"id"`
	Metadata *map[string]interface{} `json:"metadata,omitempty"`
	Name     string                  `json:"name"`
}

// FieldType defines model for FieldType.
type FieldType string

// FieldValue defines model for FieldValue.
type FieldValue struct {
	FieldId types.FieldID `json:"fieldId"`
	Value   interface{}   `json:"value"`
}

// StatusDef defines model for StatusDef.
type StatusDef struct {
	Color    string `json:"color"`
	Id       string `json:"id"`
	IsClosed bool   `json:"isClosed"`
	Name     string `json:"name"`
	Order    int    `json:"order"`
}

// Ticket defines model for Ticket.
type Ticket struct {
	AssigneeId          *string      `json:"assigneeId,omitempty"`
	CreatedAt           time.Time    `json:"createdAt"`
	Description         *string      `json:"description,omitempty"`
	Fields              []FieldValue `json:"fields"`
	Id                  string       `json:"id"`
	ReporterSlackUserId *string      `json:"reporterSlackUserId,omitempty"`
	SeqNum              int64        `json:"seqNum"`
	SlackChannelId      *string      `json:"slackChannelId,omitempty"`
	SlackThreadTs       *string      `json:"slackThreadTs,omitempty"`
	StatusId            string       `json:"statusId"`
	Title               string       `json:"title"`
	UpdatedAt           time.Time    `json:"updatedAt"`
}

// TicketConfig defines model for TicketConfig.
type TicketConfig struct {
	ClosedStatusIds []string `json:"closedStatusIds"`
	DefaultStatusId string   `json:"defaultStatusId"`
}

// UpdateTicketRequest defines model for UpdateTicketRequest.
type UpdateTicketRequest struct {
	AssigneeId  *string       `json:"assigneeId,omitempty"`
	Description *string       `json:"description,omitempty"`
	Fields      *[]FieldValue `json:"fields,omitempty"`
	StatusId    *string       `json:"statusId,omitempty"`
	Title       *string       `json:"title,omitempty"`
}

// Workspace defines model for Workspace.
type Workspace struct {
	Id   string `json:"id"`
	Name string `json:"name"`
}

// WorkspaceConfig defines model for WorkspaceConfig.
type WorkspaceConfig struct {
	Fields       []FieldDefinition `json:"fields"`
	Labels       EntityLabels      `json:"labels"`
	Statuses     []StatusDef       `json:"statuses"`
	TicketConfig TicketConfig      `json:"ticketConfig"`
}

// TicketId defines model for TicketId.
type TicketId = string

// WorkspaceId defines model for WorkspaceId.
type WorkspaceId = string

// ListTicketsParams defines parameters for ListTickets.
type ListTicketsParams struct {
	StatusId *string `form:"statusId,omitempty" json:"statusId,omitempty"`
	IsClosed *bool   `form:"isClosed,omitempty" json:"isClosed,omitempty"`
}

// CreateTicketJSONRequestBody defines body for CreateTicket for application/json ContentType.
type CreateTicketJSONRequestBody = CreateTicketRequest

// UpdateTicketJSONRequestBody defines body for UpdateTicket for application/json ContentType.
type UpdateTicketJSONRequestBody = UpdateTicketRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /api/v1/health)
	GetHealth(w http.ResponseWriter, r *http.Request)

	// (GET /api/v1/ws)
	ListWorkspaces(w http.ResponseWriter, r *http.Request)

	// (GET /api/v1/ws/{workspaceId})
	GetWorkspace(w http.ResponseWriter, r *http.Request, workspaceId WorkspaceId)

	// (GET /api/v1/ws/{workspaceId}/config)
	GetWorkspaceConfig(w http.ResponseWriter, r *http.Request, workspaceId WorkspaceId)

	// (GET /api/v1/ws/{workspaceId}/tickets)
	ListTickets(w http.ResponseWriter, r *http.Request, workspaceId WorkspaceId, params ListTicketsParams)

	// (POST /api/v1/ws/{workspaceId}/tickets)
	CreateTicket(w http.ResponseWriter, r *http.Request, workspaceId WorkspaceId)

	// (DELETE /api/v1/ws/{workspaceId}/tickets/{ticketId})
	DeleteTicket(w http.ResponseWriter, r *http.Request, workspaceId WorkspaceId, ticketId TicketId)

	// (GET /api/v1/ws/{workspaceId}/tickets/{ticketId})
	GetTicket(w http.ResponseWriter, r *http.Request, workspaceId WorkspaceId, ticketId TicketId)

	// (PATCH /api/v1/ws/{workspaceId}/tickets/{ticketId})
	UpdateTicket(w http.ResponseWriter, r *http.Request, workspaceId WorkspaceId, ticketId TicketId)

	// (GET /api/v1/ws/{workspaceId}/tickets/{ticketId}/comments)
	ListComments(w http.ResponseWriter, r *http.Request, workspaceId WorkspaceId, ticketId TicketId)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// (GET /api/v1/health)
func (_ Unimplemented) GetHealth(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /api/v1/ws)
func (_ Unimplemented) ListWorkspaces(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /api/v1/ws/{workspaceId})
func (_ Unimplemented) GetWorkspace(w http.ResponseWriter, r *http.Request, workspaceId WorkspaceId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /api/v1/ws/{workspaceId}/config)
func (_ Unimplemented) GetWorkspaceConfig(w http.ResponseWriter, r *http.Request, workspaceId WorkspaceId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /api/v1/ws/{workspaceId}/tickets)
func (_ Unimplemented) ListTickets(w http.ResponseWriter, r *http.Request, workspaceId WorkspaceId, params ListTicketsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /api/v1/ws/{workspaceId}/tickets)
func (_ Unimplemented) CreateTicket(w http.ResponseWriter, r *http.Request, workspaceId WorkspaceId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (DELETE /api/v1/ws/{workspaceId}/tickets/{ticketId})
func (_ Unimplemented) DeleteTicket(w http.ResponseWriter, r *http.Request, workspaceId WorkspaceId, ticketId TicketId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /api/v1/ws/{workspaceId}/tickets/{ticketId})
func (_ Unimplemented) GetTicket(w http.ResponseWriter, r *http.Request, workspaceId WorkspaceId, ticketId TicketId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (PATCH /api/v1/ws/{workspaceId}/tickets/{ticketId})
func (_ Unimplemented) UpdateTicket(w http.ResponseWriter, r *http.Request, workspaceId WorkspaceId, ticketId TicketId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /api/v1/ws/{workspaceId}/tickets/{ticketId}/comments)
func (_ Unimplemented) ListComments(w http.ResponseWriter, r *http.Request, workspaceId WorkspaceId, ticketId TicketId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListWorkspaces operation middleware
func (siw *ServerInterfaceWrapper) ListWorkspaces(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListWorkspaces(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetWorkspace operation middleware
func (siw *ServerInterfaceWrapper) GetWorkspace(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "workspaceId" -------------
	var workspaceId WorkspaceId

	err = runtime.BindStyledParameterWithOptions("simple", "workspaceId", chi.URLParam(r, "workspaceId"), &workspaceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "workspaceId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetWorkspace(w, r, workspaceId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetWorkspaceConfig operation middleware
func (siw *ServerInterfaceWrapper) GetWorkspaceConfig(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "workspaceId" -------------
	var workspaceId WorkspaceId

	err = runtime.BindStyledParameterWithOptions("simple", "workspaceId", chi.URLParam(r, "workspaceId"), &workspaceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "workspaceId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetWorkspaceConfig(w, r, workspaceId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListTickets operation middleware
func (siw *ServerInterfaceWrapper) ListTickets(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "workspaceId" -------------
	var workspaceId WorkspaceId

	err = runtime.BindStyledParameterWithOptions("simple", "workspaceId", chi.URLParam(r, "workspaceId"), &workspaceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "workspaceId", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ListTicketsParams

	// ------------- Optional query parameter "statusId" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "statusId", r.URL.Query(), &params.StatusId, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "statusId", Err: err})
		return
	}

	// ------------- Optional query parameter "isClosed" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "isClosed", r.URL.Query(), &params.IsClosed, runtime.BindQueryParameterOptions{Type: "boolean", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "isClosed", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListTickets(w, r, workspaceId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateTicket operation middleware
func (siw *ServerInterfaceWrapper) CreateTicket(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "workspaceId" -------------
	var workspaceId WorkspaceId

	err = runtime.BindStyledParameterWithOptions("simple", "workspaceId", chi.URLParam(r, "workspaceId"), &workspaceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "workspaceId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateTicket(w, r, workspaceId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteTicket operation middleware
func (siw *ServerInterfaceWrapper) DeleteTicket(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "workspaceId" -------------
	var workspaceId WorkspaceId

	err = runtime.BindStyledParameterWithOptions("simple", "workspaceId", chi.URLParam(r, "workspaceId"), &workspaceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "workspaceId", Err: err})
		return
	}

	// ------------- Path parameter "ticketId" -------------
	var ticketId TicketId

	err = runtime.BindStyledParameterWithOptions("simple", "ticketId", chi.URLParam(r, "ticketId"), &ticketId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "ticketId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteTicket(w, r, workspaceId, ticketId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTicket operation middleware
func (siw *ServerInterfaceWrapper) GetTicket(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "workspaceId" -------------
	var workspaceId WorkspaceId

	err = runtime.BindStyledParameterWithOptions("simple", "workspaceId", chi.URLParam(r, "workspaceId"), &workspaceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "workspaceId", Err: err})
		return
	}

	// ------------- Path parameter "ticketId" -------------
	var ticketId TicketId

	err = runtime.BindStyledParameterWithOptions("simple", "ticketId", chi.URLParam(r, "ticketId"), &ticketId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "ticketId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTicket(w, r, workspaceId, ticketId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateTicket operation middleware
func (siw *ServerInterfaceWrapper) UpdateTicket(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "workspaceId" -------------
	var workspaceId WorkspaceId

	err = runtime.BindStyledParameterWithOptions("simple", "workspaceId", chi.URLParam(r, "workspaceId"), &workspaceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "workspaceId", Err: err})
		return
	}

	// ------------- Path parameter "ticketId" -------------
	var ticketId TicketId

	err = runtime.BindStyledParameterWithOptions("simple", "ticketId", chi.URLParam(r, "ticketId"), &ticketId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "ticketId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateTicket(w, r, workspaceId, ticketId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListComments operation middleware
func (siw *ServerInterfaceWrapper) ListComments(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "workspaceId" -------------
	var workspaceId WorkspaceId

	err = runtime.BindStyledParameterWithOptions("simple", "workspaceId", chi.URLParam(r, "workspaceId"), &workspaceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "workspaceId", Err: err})
		return
	}

	// ------------- Path parameter "ticketId" -------------
	var ticketId TicketId

	err = runtime.BindStyledParameterWithOptions("simple", "ticketId", chi.URLParam(r, "ticketId"), &ticketId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "ticketId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListComments(w, r, workspaceId, ticketId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/health", wrapper.GetHealth)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/ws", wrapper.ListWorkspaces)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/ws/{workspaceId}", wrapper.GetWorkspace)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/ws/{workspaceId}/config", wrapper.GetWorkspaceConfig)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/ws/{workspaceId}/tickets", wrapper.ListTickets)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/ws/{workspaceId}/tickets", wrapper.CreateTicket)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/api/v1/ws/{workspaceId}/tickets/{ticketId}", wrapper.DeleteTicket)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/ws/{workspaceId}/tickets/{ticketId}", wrapper.GetTicket)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/api/v1/ws/{workspaceId}/tickets/{ticketId}", wrapper.UpdateTicket)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/ws/{workspaceId}/tickets/{ticketId}/comments", wrapper.ListComments)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+RZzXLbNhB+lQzaIyUqjacH3VK5aTXNxJlaaQ+ZHCBiJSEmARoA47gavnsHAAmCIiiR",
	"luqm05MtYbG737d/ALRHCc9yzoApieZ7lGOBM1AgzKcVTe5ALYn+nzI0RzlWOxQhhjNAc6Tq5QgJuC+o",
	"AILmShQQIZnsIMN6n3rMtaxUgrItKssI/cnFncxxAr2KHzyJMbrLetF4v+BZBkwZWILnIBQFs7Dm5DGw",
	"PUKJAKyAvDZ7NlxkWKE5IljBRNEMUNTdQklQk0xxcvdBgliSMAkNqI9aR3tHZF30HfrkbPP1Z0iUNrIw",
	"qzZIv8N9ATIAFktJtwxgGXaUgEwEzRXlLLi+oZASo4gqyMw/3wvYoDn6Lm5SJ65oj99o8T9wWoDeXGnD",
	"QuBHw4rCqpA9niiqUjhNlhUL0fEzU1Q9vsVrSGWXh1NAbTKf55nRUMu3uQ05bMi6hg1ltHZrnM89yWer",
	"KLDAjaqR0byx9gPhbMA7W2vOU8Ce9AADKy0YrAkDpNLkLfdyeZOHeUx4ysUYBjNQmGBlmgwmxIQHp+89",
	"pbYVddzoob4XXC+UVcUesCIzyQVfdWqxIluD0O0CUi0eoaxIFZ24j4U0y7pn6U8i9Uw0+Lwy7ZBlKj5U",
	"oxH6OtnySfWl/iOnRtHy2l+b0CznwnYi3dXnaEvVrlhPE57F2SSjfxUKMxrLHeQ7ECTO77Yx4RmmLDZK",
	"DV1fKucOqau9qyVCBN6aNnOt0+7sTKBykXLZl+P9lSYI+HYoU7AFcTTNrW/1Xs90COPKtatR7f4JE+5Z",
	"J0RPFATolAJxe3Ss6qq4f6frxcNGmfrxqsHlAlFN3MUOMwbp8sgYX+0EYLKSYYmnjLQIFTkZF4fgkcGi",
	"bQaOc8ZFxY+4b7U/pRacbeg2UDkmF28rC+14d4EfhJXABhepuu0n6wDf4YaoYz+E4IPB9z84EHWQuzN1",
	"F++4Q8KoSeWs9iXNU8jyDkQBxlJ3vDumqHUUdDzDcE+aERLwQR0UyjFFraI6ZNe5daDTK98Kb5d9rYuy",
	"DTcxtJmCbquR+uL1+6WekCCkSWM0m76czuwJEBjOKZqjV9PZ9BWKzIw2dMQ4p/GXl/EOcKrH9h5t7YDR",
	"AcU6HjpP0S+gfrUSGovMOat4/WE2sxOWqerWhfM8pYnZGn+Wtp6ay1s7UywVpxOykgvz0apddPOb/raM",
	"HLIH2YvqLZXKZbO8LLSHRu/Q9GvKuZN+B3x4yp/ISbz3rtvlsbg3XkWth4KPYTCNSOxf+ctPZ7I7kLgw",
	"+Ahdza46dyv0jqsXb3jByAl64sRV/UmWXDF/61y57vSPMGY72/HSW1UyZ3EVVW9J9wWIx+YxyTsUHXmV",
	"Cu91R/DAXncNODtI7Xbh8TWoV1Q3gVONolY7tEsMCXuEci4DIfUfpi6Q/+Yg91P1aHeR1A+9nJVtxvQF",
	"v+wE9uXFXKjD1mXfOkcuVnnxvn6oLa2yFBR0g3Ztvr9E0KKT4u5hOVA7AcTWNTI0Kfs687+PbfYM6TOi",
	"eLFKdl2m/FvUM5N1+UoPXQkHVfq3FKpxRa59yOofdHpH7qIW+s+Uw+FLXgNy0Jysfw46NSid4ktOyrIs",
	"/w4AAP//03rsbWsbAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
