// Package http provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package http

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/m-mizutani/shepherd/pkg/domain/types"
	"github.com/oapi-codegen/runtime"
)

// Defines values for CreateSourceRequestProvider.
const (
	CreateSourceRequestProviderNotion CreateSourceRequestProvider = "notion"
)

// Defines values for FieldType.
const (
	Date        FieldType = "date"
	MultiSelect FieldType = "multi-select"
	MultiUser   FieldType = "multi-user"
	Number      FieldType = "number"
	Select      FieldType = "select"
	Text        FieldType = "text"
	Url         FieldType = "url"
	User        FieldType = "user"
)

// Defines values for NotionSourceObjectType.
const (
	Database NotionSourceObjectType = "database"
	Page     NotionSourceObjectType = "page"
)

// Defines values for PromptTemplateErrorError.
const (
	InvalidTemplate PromptTemplateErrorError = "invalid_template"
)

// Defines values for PromptVersionConflictError.
const (
	VersionConflict PromptVersionConflictError = "version_conflict"
)

// Defines values for SourceProvider.
const (
	SourceProviderNotion SourceProvider = "notion"
)

// Defines values for ToolStateReason.
const (
	GateBlocked         ToolStateReason = "gate_blocked"
	ProviderUnavailable ToolStateReason = "provider_unavailable"
	WorkspaceDisabled   ToolStateReason = "workspace_disabled"
)

// Comment defines model for Comment.
type Comment struct {
	Body        string    `json:"body"`
	CreatedAt   time.Time `json:"createdAt"`
	Id          string    `json:"id"`
	SlackUserId string    `json:"slackUserId"`
}

// CreateSourceRequest defines model for CreateSourceRequest.
type CreateSourceRequest struct {
	Description *string                     `json:"description,omitempty"`
	Provider    CreateSourceRequestProvider `json:"provider"`
	Url         string                      `json:"url"`
}

// CreateSourceRequestProvider defines model for CreateSourceRequest.Provider.
type CreateSourceRequestProvider string

// CreateTicketRequest defines model for CreateTicketRequest.
type CreateTicketRequest struct {
	AssigneeId  *string       `json:"assigneeId,omitempty"`
	Description *string       `json:"description,omitempty"`
	Fields      *[]FieldValue `json:"fields,omitempty"`
	StatusId    *string       `json:"statusId,omitempty"`
	Title       string        `json:"title"`
}

// EntityLabels defines model for EntityLabels.
type EntityLabels struct {
	Description string `json:"description"`
	Ticket      string `json:"ticket"`
	Title       string `json:"title"`
}

// FieldDefinition defines model for FieldDefinition.
type FieldDefinition struct {
	Description *string        `json:"description,omitempty"`
	Id          string         `json:"id"`
	Name        string         `json:"name"`
	Options     *[]FieldOption `json:"options,omitempty"`
	Required    bool           `json:"required"`
	Type        FieldType      `json:"type"`
}

// FieldOption defines model for FieldOption.
type FieldOption struct {
	Color    *string                 `json:"color,omitempty"`
	Id       string                  `json:"id"`
	Metadata *map[string]interface{} `json:"metadata,omitempty"`
	Name     string                  `json:"name"`
}

// FieldType defines model for FieldType.
type FieldType string

// FieldValue defines model for FieldValue.
type FieldValue struct {
	FieldId types.FieldID `json:"fieldId"`
	Value   interface{}   `json:"value"`
}

// NotionSource defines model for NotionSource.
type NotionSource struct {
	ObjectId   string                 `json:"objectId"`
	ObjectType NotionSourceObjectType `json:"objectType"`
	Title      *string                `json:"title,omitempty"`
	Url        string                 `json:"url"`
}

// NotionSourceObjectType defines model for NotionSource.ObjectType.
type NotionSourceObjectType string

// PromptAuthor defines model for PromptAuthor.
type PromptAuthor struct {
	Email *string `json:"email,omitempty"`
	Name  string  `json:"name"`
}

// PromptDetail defines model for PromptDetail.
type PromptDetail struct {
	Content        string        `json:"content"`
	DefaultContent string        `json:"defaultContent"`
	Id             string        `json:"id"`
	IsOverride     bool          `json:"isOverride"`
	UpdatedAt      *time.Time    `json:"updatedAt"`
	UpdatedBy      *PromptAuthor `json:"updatedBy,omitempty"`
	Variables      []string      `json:"variables"`

	// Version 0 when the embedded default is in force, else the latest stored version.
	Version int `json:"version"`
}

// PromptSlot defines model for PromptSlot.
type PromptSlot struct {
	// Configured true when at least one override version exists.
	Configured bool `json:"configured"`

	// Customizable false for slots that are placeholders only.
	Customizable bool   `json:"customizable"`
	Description  string `json:"description"`

	// Id Stable identifier (e.g. "triage").
	Id        string        `json:"id"`
	Label     string        `json:"label"`
	Length    int           `json:"length"`
	UpdatedAt *time.Time    `json:"updatedAt"`
	UpdatedBy *PromptAuthor `json:"updatedBy,omitempty"`

	// Version Current version (0 when no override exists yet).
	Version int `json:"version"`
}

// PromptTemplateError defines model for PromptTemplateError.
type PromptTemplateError struct {
	Error  PromptTemplateErrorError `json:"error"`
	Reason string                   `json:"reason"`
}

// PromptTemplateErrorError defines model for PromptTemplateError.Error.
type PromptTemplateErrorError string

// PromptVersion defines model for PromptVersion.
type PromptVersion struct {
	Content   string        `json:"content"`
	Current   bool          `json:"current"`
	UpdatedAt time.Time     `json:"updatedAt"`
	UpdatedBy *PromptAuthor `json:"updatedBy,omitempty"`
	Version   int           `json:"version"`
}

// PromptVersionConflict defines model for PromptVersionConflict.
type PromptVersionConflict struct {
	CurrentVersion int                        `json:"currentVersion"`
	Error          PromptVersionConflictError `json:"error"`
}

// PromptVersionConflictError defines model for PromptVersionConflict.Error.
type PromptVersionConflictError string

// SlackUserInfo defines model for SlackUserInfo.
type SlackUserInfo struct {
	Email    *string `json:"email,omitempty"`
	Id       string  `json:"id"`
	ImageUrl *string `json:"imageUrl,omitempty"`
	Name     string  `json:"name"`
}

// Source defines model for Source.
type Source struct {
	CreatedAt   time.Time      `json:"createdAt"`
	CreatedBy   *string        `json:"createdBy,omitempty"`
	Description *string        `json:"description,omitempty"`
	Id          string         `json:"id"`
	Notion      *NotionSource  `json:"notion,omitempty"`
	Provider    SourceProvider `json:"provider"`
	WorkspaceId string         `json:"workspaceId"`
}

// SourceProvider defines model for Source.Provider.
type SourceProvider string

// StatusDef defines model for StatusDef.
type StatusDef struct {
	Color    string `json:"color"`
	Id       string `json:"id"`
	IsClosed bool   `json:"isClosed"`
	Name     string `json:"name"`
	Order    int    `json:"order"`
}

// Ticket defines model for Ticket.
type Ticket struct {
	AssigneeId          *string      `json:"assigneeId,omitempty"`
	CreatedAt           time.Time    `json:"createdAt"`
	Description         *string      `json:"description,omitempty"`
	Fields              []FieldValue `json:"fields"`
	Id                  string       `json:"id"`
	ReporterSlackUserId *string      `json:"reporterSlackUserId,omitempty"`
	SeqNum              int64        `json:"seqNum"`
	SlackChannelId      *string      `json:"slackChannelId,omitempty"`
	SlackThreadTs       *string      `json:"slackThreadTs,omitempty"`
	StatusId            string       `json:"statusId"`
	Title               string       `json:"title"`
	UpdatedAt           time.Time    `json:"updatedAt"`
}

// TicketConfig defines model for TicketConfig.
type TicketConfig struct {
	ClosedStatusIds []string `json:"closedStatusIds"`
	DefaultStatusId string   `json:"defaultStatusId"`
}

// ToolState defines model for ToolState.
type ToolState struct {
	Available      bool             `json:"available"`
	DefaultEnabled bool             `json:"defaultEnabled"`
	Enabled        bool             `json:"enabled"`
	ProviderId     string           `json:"providerId"`
	Reason         *ToolStateReason `json:"reason,omitempty"`
}

// ToolStateReason defines model for ToolState.Reason.
type ToolStateReason string

// UpdateSourceRequest defines model for UpdateSourceRequest.
type UpdateSourceRequest struct {
	Description string `json:"description"`
}

// UpdateTicketRequest defines model for UpdateTicketRequest.
type UpdateTicketRequest struct {
	AssigneeId  *string       `json:"assigneeId,omitempty"`
	Description *string       `json:"description,omitempty"`
	Fields      *[]FieldValue `json:"fields,omitempty"`
	StatusId    *string       `json:"statusId,omitempty"`
	Title       *string       `json:"title,omitempty"`
}

// Workspace defines model for Workspace.
type Workspace struct {
	Id   string `json:"id"`
	Name string `json:"name"`
}

// WorkspaceConfig defines model for WorkspaceConfig.
type WorkspaceConfig struct {
	Fields       []FieldDefinition `json:"fields"`
	Labels       EntityLabels      `json:"labels"`
	Statuses     []StatusDef       `json:"statuses"`
	TicketConfig TicketConfig      `json:"ticketConfig"`
}

// PromptId defines model for PromptId.
type PromptId = string

// TicketId defines model for TicketId.
type TicketId = string

// WorkspaceId defines model for WorkspaceId.
type WorkspaceId = string

// SavePromptJSONBody defines parameters for SavePrompt.
type SavePromptJSONBody struct {
	Content string `json:"content"`

	// Version The version number the caller is writing. Must equal current+1 (or 1 when no override exists yet); otherwise 409 Conflict.
	Version int `json:"version"`
}

// RestorePromptJSONBody defines parameters for RestorePrompt.
type RestorePromptJSONBody struct {
	// TargetVersion The version to restore from.
	TargetVersion int `json:"targetVersion"`

	// Version The new version number to write the restored content as. Must equal current+1.
	Version int `json:"version"`
}

// ListTicketsParams defines parameters for ListTickets.
type ListTicketsParams struct {
	StatusId *string `form:"statusId,omitempty" json:"statusId,omitempty"`
	IsClosed *bool   `form:"isClosed,omitempty" json:"isClosed,omitempty"`
}

// SetToolEnabledJSONBody defines parameters for SetToolEnabled.
type SetToolEnabledJSONBody struct {
	Enabled bool `json:"enabled"`
}

// SavePromptJSONRequestBody defines body for SavePrompt for application/json ContentType.
type SavePromptJSONRequestBody SavePromptJSONBody

// RestorePromptJSONRequestBody defines body for RestorePrompt for application/json ContentType.
type RestorePromptJSONRequestBody RestorePromptJSONBody

// CreateSourceJSONRequestBody defines body for CreateSource for application/json ContentType.
type CreateSourceJSONRequestBody = CreateSourceRequest

// UpdateSourceJSONRequestBody defines body for UpdateSource for application/json ContentType.
type UpdateSourceJSONRequestBody = UpdateSourceRequest

// CreateTicketJSONRequestBody defines body for CreateTicket for application/json ContentType.
type CreateTicketJSONRequestBody = CreateTicketRequest

// UpdateTicketJSONRequestBody defines body for UpdateTicket for application/json ContentType.
type UpdateTicketJSONRequestBody = UpdateTicketRequest

// SetToolEnabledJSONRequestBody defines body for SetToolEnabled for application/json ContentType.
type SetToolEnabledJSONRequestBody SetToolEnabledJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /api/v1/health)
	GetHealth(w http.ResponseWriter, r *http.Request)

	// (GET /api/v1/ws)
	ListWorkspaces(w http.ResponseWriter, r *http.Request)

	// (GET /api/v1/ws/{workspaceId})
	GetWorkspace(w http.ResponseWriter, r *http.Request, workspaceId WorkspaceId)

	// (GET /api/v1/ws/{workspaceId}/config)
	GetWorkspaceConfig(w http.ResponseWriter, r *http.Request, workspaceId WorkspaceId)

	// (GET /api/v1/ws/{workspaceId}/prompts)
	ListPrompts(w http.ResponseWriter, r *http.Request, workspaceId WorkspaceId)

	// (GET /api/v1/ws/{workspaceId}/prompts/{promptId})
	GetPrompt(w http.ResponseWriter, r *http.Request, workspaceId WorkspaceId, promptId PromptId)

	// (PUT /api/v1/ws/{workspaceId}/prompts/{promptId})
	SavePrompt(w http.ResponseWriter, r *http.Request, workspaceId WorkspaceId, promptId PromptId)

	// (GET /api/v1/ws/{workspaceId}/prompts/{promptId}/history)
	ListPromptHistory(w http.ResponseWriter, r *http.Request, workspaceId WorkspaceId, promptId PromptId)

	// (POST /api/v1/ws/{workspaceId}/prompts/{promptId}/restore)
	RestorePrompt(w http.ResponseWriter, r *http.Request, workspaceId WorkspaceId, promptId PromptId)

	// (GET /api/v1/ws/{workspaceId}/slack/users)
	ListSlackUsers(w http.ResponseWriter, r *http.Request, workspaceId WorkspaceId)

	// (GET /api/v1/ws/{workspaceId}/slack/users/{userId})
	GetSlackUserInfo(w http.ResponseWriter, r *http.Request, workspaceId WorkspaceId, userId string)

	// (GET /api/v1/ws/{workspaceId}/sources)
	ListSources(w http.ResponseWriter, r *http.Request, workspaceId WorkspaceId)

	// (POST /api/v1/ws/{workspaceId}/sources)
	CreateSource(w http.ResponseWriter, r *http.Request, workspaceId WorkspaceId)

	// (DELETE /api/v1/ws/{workspaceId}/sources/{sourceId})
	DeleteSource(w http.ResponseWriter, r *http.Request, workspaceId WorkspaceId, sourceId string)

	// (PATCH /api/v1/ws/{workspaceId}/sources/{sourceId})
	UpdateSource(w http.ResponseWriter, r *http.Request, workspaceId WorkspaceId, sourceId string)

	// (GET /api/v1/ws/{workspaceId}/tickets)
	ListTickets(w http.ResponseWriter, r *http.Request, workspaceId WorkspaceId, params ListTicketsParams)

	// (POST /api/v1/ws/{workspaceId}/tickets)
	CreateTicket(w http.ResponseWriter, r *http.Request, workspaceId WorkspaceId)

	// (DELETE /api/v1/ws/{workspaceId}/tickets/{ticketId})
	DeleteTicket(w http.ResponseWriter, r *http.Request, workspaceId WorkspaceId, ticketId TicketId)

	// (GET /api/v1/ws/{workspaceId}/tickets/{ticketId})
	GetTicket(w http.ResponseWriter, r *http.Request, workspaceId WorkspaceId, ticketId TicketId)

	// (PATCH /api/v1/ws/{workspaceId}/tickets/{ticketId})
	UpdateTicket(w http.ResponseWriter, r *http.Request, workspaceId WorkspaceId, ticketId TicketId)

	// (GET /api/v1/ws/{workspaceId}/tickets/{ticketId}/comments)
	ListComments(w http.ResponseWriter, r *http.Request, workspaceId WorkspaceId, ticketId TicketId)

	// (GET /api/v1/ws/{workspaceId}/tools)
	ListToolSettings(w http.ResponseWriter, r *http.Request, workspaceId WorkspaceId)

	// (PUT /api/v1/ws/{workspaceId}/tools/{providerId})
	SetToolEnabled(w http.ResponseWriter, r *http.Request, workspaceId WorkspaceId, providerId string)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// (GET /api/v1/health)
func (_ Unimplemented) GetHealth(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /api/v1/ws)
func (_ Unimplemented) ListWorkspaces(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /api/v1/ws/{workspaceId})
func (_ Unimplemented) GetWorkspace(w http.ResponseWriter, r *http.Request, workspaceId WorkspaceId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /api/v1/ws/{workspaceId}/config)
func (_ Unimplemented) GetWorkspaceConfig(w http.ResponseWriter, r *http.Request, workspaceId WorkspaceId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /api/v1/ws/{workspaceId}/prompts)
func (_ Unimplemented) ListPrompts(w http.ResponseWriter, r *http.Request, workspaceId WorkspaceId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /api/v1/ws/{workspaceId}/prompts/{promptId})
func (_ Unimplemented) GetPrompt(w http.ResponseWriter, r *http.Request, workspaceId WorkspaceId, promptId PromptId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (PUT /api/v1/ws/{workspaceId}/prompts/{promptId})
func (_ Unimplemented) SavePrompt(w http.ResponseWriter, r *http.Request, workspaceId WorkspaceId, promptId PromptId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /api/v1/ws/{workspaceId}/prompts/{promptId}/history)
func (_ Unimplemented) ListPromptHistory(w http.ResponseWriter, r *http.Request, workspaceId WorkspaceId, promptId PromptId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /api/v1/ws/{workspaceId}/prompts/{promptId}/restore)
func (_ Unimplemented) RestorePrompt(w http.ResponseWriter, r *http.Request, workspaceId WorkspaceId, promptId PromptId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /api/v1/ws/{workspaceId}/slack/users)
func (_ Unimplemented) ListSlackUsers(w http.ResponseWriter, r *http.Request, workspaceId WorkspaceId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /api/v1/ws/{workspaceId}/slack/users/{userId})
func (_ Unimplemented) GetSlackUserInfo(w http.ResponseWriter, r *http.Request, workspaceId WorkspaceId, userId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /api/v1/ws/{workspaceId}/sources)
func (_ Unimplemented) ListSources(w http.ResponseWriter, r *http.Request, workspaceId WorkspaceId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /api/v1/ws/{workspaceId}/sources)
func (_ Unimplemented) CreateSource(w http.ResponseWriter, r *http.Request, workspaceId WorkspaceId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (DELETE /api/v1/ws/{workspaceId}/sources/{sourceId})
func (_ Unimplemented) DeleteSource(w http.ResponseWriter, r *http.Request, workspaceId WorkspaceId, sourceId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (PATCH /api/v1/ws/{workspaceId}/sources/{sourceId})
func (_ Unimplemented) UpdateSource(w http.ResponseWriter, r *http.Request, workspaceId WorkspaceId, sourceId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /api/v1/ws/{workspaceId}/tickets)
func (_ Unimplemented) ListTickets(w http.ResponseWriter, r *http.Request, workspaceId WorkspaceId, params ListTicketsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /api/v1/ws/{workspaceId}/tickets)
func (_ Unimplemented) CreateTicket(w http.ResponseWriter, r *http.Request, workspaceId WorkspaceId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (DELETE /api/v1/ws/{workspaceId}/tickets/{ticketId})
func (_ Unimplemented) DeleteTicket(w http.ResponseWriter, r *http.Request, workspaceId WorkspaceId, ticketId TicketId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /api/v1/ws/{workspaceId}/tickets/{ticketId})
func (_ Unimplemented) GetTicket(w http.ResponseWriter, r *http.Request, workspaceId WorkspaceId, ticketId TicketId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (PATCH /api/v1/ws/{workspaceId}/tickets/{ticketId})
func (_ Unimplemented) UpdateTicket(w http.ResponseWriter, r *http.Request, workspaceId WorkspaceId, ticketId TicketId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /api/v1/ws/{workspaceId}/tickets/{ticketId}/comments)
func (_ Unimplemented) ListComments(w http.ResponseWriter, r *http.Request, workspaceId WorkspaceId, ticketId TicketId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /api/v1/ws/{workspaceId}/tools)
func (_ Unimplemented) ListToolSettings(w http.ResponseWriter, r *http.Request, workspaceId WorkspaceId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (PUT /api/v1/ws/{workspaceId}/tools/{providerId})
func (_ Unimplemented) SetToolEnabled(w http.ResponseWriter, r *http.Request, workspaceId WorkspaceId, providerId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListWorkspaces operation middleware
func (siw *ServerInterfaceWrapper) ListWorkspaces(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListWorkspaces(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetWorkspace operation middleware
func (siw *ServerInterfaceWrapper) GetWorkspace(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "workspaceId" -------------
	var workspaceId WorkspaceId

	err = runtime.BindStyledParameterWithOptions("simple", "workspaceId", chi.URLParam(r, "workspaceId"), &workspaceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "workspaceId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetWorkspace(w, r, workspaceId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetWorkspaceConfig operation middleware
func (siw *ServerInterfaceWrapper) GetWorkspaceConfig(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "workspaceId" -------------
	var workspaceId WorkspaceId

	err = runtime.BindStyledParameterWithOptions("simple", "workspaceId", chi.URLParam(r, "workspaceId"), &workspaceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "workspaceId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetWorkspaceConfig(w, r, workspaceId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListPrompts operation middleware
func (siw *ServerInterfaceWrapper) ListPrompts(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "workspaceId" -------------
	var workspaceId WorkspaceId

	err = runtime.BindStyledParameterWithOptions("simple", "workspaceId", chi.URLParam(r, "workspaceId"), &workspaceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "workspaceId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListPrompts(w, r, workspaceId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetPrompt operation middleware
func (siw *ServerInterfaceWrapper) GetPrompt(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "workspaceId" -------------
	var workspaceId WorkspaceId

	err = runtime.BindStyledParameterWithOptions("simple", "workspaceId", chi.URLParam(r, "workspaceId"), &workspaceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "workspaceId", Err: err})
		return
	}

	// ------------- Path parameter "promptId" -------------
	var promptId PromptId

	err = runtime.BindStyledParameterWithOptions("simple", "promptId", chi.URLParam(r, "promptId"), &promptId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "promptId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPrompt(w, r, workspaceId, promptId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SavePrompt operation middleware
func (siw *ServerInterfaceWrapper) SavePrompt(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "workspaceId" -------------
	var workspaceId WorkspaceId

	err = runtime.BindStyledParameterWithOptions("simple", "workspaceId", chi.URLParam(r, "workspaceId"), &workspaceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "workspaceId", Err: err})
		return
	}

	// ------------- Path parameter "promptId" -------------
	var promptId PromptId

	err = runtime.BindStyledParameterWithOptions("simple", "promptId", chi.URLParam(r, "promptId"), &promptId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "promptId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SavePrompt(w, r, workspaceId, promptId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListPromptHistory operation middleware
func (siw *ServerInterfaceWrapper) ListPromptHistory(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "workspaceId" -------------
	var workspaceId WorkspaceId

	err = runtime.BindStyledParameterWithOptions("simple", "workspaceId", chi.URLParam(r, "workspaceId"), &workspaceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "workspaceId", Err: err})
		return
	}

	// ------------- Path parameter "promptId" -------------
	var promptId PromptId

	err = runtime.BindStyledParameterWithOptions("simple", "promptId", chi.URLParam(r, "promptId"), &promptId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "promptId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListPromptHistory(w, r, workspaceId, promptId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RestorePrompt operation middleware
func (siw *ServerInterfaceWrapper) RestorePrompt(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "workspaceId" -------------
	var workspaceId WorkspaceId

	err = runtime.BindStyledParameterWithOptions("simple", "workspaceId", chi.URLParam(r, "workspaceId"), &workspaceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "workspaceId", Err: err})
		return
	}

	// ------------- Path parameter "promptId" -------------
	var promptId PromptId

	err = runtime.BindStyledParameterWithOptions("simple", "promptId", chi.URLParam(r, "promptId"), &promptId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "promptId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RestorePrompt(w, r, workspaceId, promptId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListSlackUsers operation middleware
func (siw *ServerInterfaceWrapper) ListSlackUsers(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "workspaceId" -------------
	var workspaceId WorkspaceId

	err = runtime.BindStyledParameterWithOptions("simple", "workspaceId", chi.URLParam(r, "workspaceId"), &workspaceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "workspaceId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListSlackUsers(w, r, workspaceId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSlackUserInfo operation middleware
func (siw *ServerInterfaceWrapper) GetSlackUserInfo(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "workspaceId" -------------
	var workspaceId WorkspaceId

	err = runtime.BindStyledParameterWithOptions("simple", "workspaceId", chi.URLParam(r, "workspaceId"), &workspaceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "workspaceId", Err: err})
		return
	}

	// ------------- Path parameter "userId" -------------
	var userId string

	err = runtime.BindStyledParameterWithOptions("simple", "userId", chi.URLParam(r, "userId"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "userId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSlackUserInfo(w, r, workspaceId, userId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListSources operation middleware
func (siw *ServerInterfaceWrapper) ListSources(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "workspaceId" -------------
	var workspaceId WorkspaceId

	err = runtime.BindStyledParameterWithOptions("simple", "workspaceId", chi.URLParam(r, "workspaceId"), &workspaceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "workspaceId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListSources(w, r, workspaceId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateSource operation middleware
func (siw *ServerInterfaceWrapper) CreateSource(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "workspaceId" -------------
	var workspaceId WorkspaceId

	err = runtime.BindStyledParameterWithOptions("simple", "workspaceId", chi.URLParam(r, "workspaceId"), &workspaceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "workspaceId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateSource(w, r, workspaceId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteSource operation middleware
func (siw *ServerInterfaceWrapper) DeleteSource(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "workspaceId" -------------
	var workspaceId WorkspaceId

	err = runtime.BindStyledParameterWithOptions("simple", "workspaceId", chi.URLParam(r, "workspaceId"), &workspaceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "workspaceId", Err: err})
		return
	}

	// ------------- Path parameter "sourceId" -------------
	var sourceId string

	err = runtime.BindStyledParameterWithOptions("simple", "sourceId", chi.URLParam(r, "sourceId"), &sourceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sourceId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteSource(w, r, workspaceId, sourceId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateSource operation middleware
func (siw *ServerInterfaceWrapper) UpdateSource(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "workspaceId" -------------
	var workspaceId WorkspaceId

	err = runtime.BindStyledParameterWithOptions("simple", "workspaceId", chi.URLParam(r, "workspaceId"), &workspaceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "workspaceId", Err: err})
		return
	}

	// ------------- Path parameter "sourceId" -------------
	var sourceId string

	err = runtime.BindStyledParameterWithOptions("simple", "sourceId", chi.URLParam(r, "sourceId"), &sourceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sourceId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateSource(w, r, workspaceId, sourceId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListTickets operation middleware
func (siw *ServerInterfaceWrapper) ListTickets(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "workspaceId" -------------
	var workspaceId WorkspaceId

	err = runtime.BindStyledParameterWithOptions("simple", "workspaceId", chi.URLParam(r, "workspaceId"), &workspaceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "workspaceId", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ListTicketsParams

	// ------------- Optional query parameter "statusId" -------------

	err = runtime.BindQueryParameter("form", true, false, "statusId", r.URL.Query(), &params.StatusId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "statusId", Err: err})
		return
	}

	// ------------- Optional query parameter "isClosed" -------------

	err = runtime.BindQueryParameter("form", true, false, "isClosed", r.URL.Query(), &params.IsClosed)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "isClosed", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListTickets(w, r, workspaceId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateTicket operation middleware
func (siw *ServerInterfaceWrapper) CreateTicket(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "workspaceId" -------------
	var workspaceId WorkspaceId

	err = runtime.BindStyledParameterWithOptions("simple", "workspaceId", chi.URLParam(r, "workspaceId"), &workspaceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "workspaceId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateTicket(w, r, workspaceId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteTicket operation middleware
func (siw *ServerInterfaceWrapper) DeleteTicket(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "workspaceId" -------------
	var workspaceId WorkspaceId

	err = runtime.BindStyledParameterWithOptions("simple", "workspaceId", chi.URLParam(r, "workspaceId"), &workspaceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "workspaceId", Err: err})
		return
	}

	// ------------- Path parameter "ticketId" -------------
	var ticketId TicketId

	err = runtime.BindStyledParameterWithOptions("simple", "ticketId", chi.URLParam(r, "ticketId"), &ticketId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "ticketId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteTicket(w, r, workspaceId, ticketId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTicket operation middleware
func (siw *ServerInterfaceWrapper) GetTicket(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "workspaceId" -------------
	var workspaceId WorkspaceId

	err = runtime.BindStyledParameterWithOptions("simple", "workspaceId", chi.URLParam(r, "workspaceId"), &workspaceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "workspaceId", Err: err})
		return
	}

	// ------------- Path parameter "ticketId" -------------
	var ticketId TicketId

	err = runtime.BindStyledParameterWithOptions("simple", "ticketId", chi.URLParam(r, "ticketId"), &ticketId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "ticketId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTicket(w, r, workspaceId, ticketId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateTicket operation middleware
func (siw *ServerInterfaceWrapper) UpdateTicket(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "workspaceId" -------------
	var workspaceId WorkspaceId

	err = runtime.BindStyledParameterWithOptions("simple", "workspaceId", chi.URLParam(r, "workspaceId"), &workspaceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "workspaceId", Err: err})
		return
	}

	// ------------- Path parameter "ticketId" -------------
	var ticketId TicketId

	err = runtime.BindStyledParameterWithOptions("simple", "ticketId", chi.URLParam(r, "ticketId"), &ticketId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "ticketId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateTicket(w, r, workspaceId, ticketId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListComments operation middleware
func (siw *ServerInterfaceWrapper) ListComments(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "workspaceId" -------------
	var workspaceId WorkspaceId

	err = runtime.BindStyledParameterWithOptions("simple", "workspaceId", chi.URLParam(r, "workspaceId"), &workspaceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "workspaceId", Err: err})
		return
	}

	// ------------- Path parameter "ticketId" -------------
	var ticketId TicketId

	err = runtime.BindStyledParameterWithOptions("simple", "ticketId", chi.URLParam(r, "ticketId"), &ticketId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "ticketId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListComments(w, r, workspaceId, ticketId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListToolSettings operation middleware
func (siw *ServerInterfaceWrapper) ListToolSettings(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "workspaceId" -------------
	var workspaceId WorkspaceId

	err = runtime.BindStyledParameterWithOptions("simple", "workspaceId", chi.URLParam(r, "workspaceId"), &workspaceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "workspaceId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListToolSettings(w, r, workspaceId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SetToolEnabled operation middleware
func (siw *ServerInterfaceWrapper) SetToolEnabled(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "workspaceId" -------------
	var workspaceId WorkspaceId

	err = runtime.BindStyledParameterWithOptions("simple", "workspaceId", chi.URLParam(r, "workspaceId"), &workspaceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "workspaceId", Err: err})
		return
	}

	// ------------- Path parameter "providerId" -------------
	var providerId string

	err = runtime.BindStyledParameterWithOptions("simple", "providerId", chi.URLParam(r, "providerId"), &providerId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "providerId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SetToolEnabled(w, r, workspaceId, providerId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/health", wrapper.GetHealth)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/ws", wrapper.ListWorkspaces)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/ws/{workspaceId}", wrapper.GetWorkspace)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/ws/{workspaceId}/config", wrapper.GetWorkspaceConfig)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/ws/{workspaceId}/prompts", wrapper.ListPrompts)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/ws/{workspaceId}/prompts/{promptId}", wrapper.GetPrompt)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/api/v1/ws/{workspaceId}/prompts/{promptId}", wrapper.SavePrompt)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/ws/{workspaceId}/prompts/{promptId}/history", wrapper.ListPromptHistory)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/ws/{workspaceId}/prompts/{promptId}/restore", wrapper.RestorePrompt)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/ws/{workspaceId}/slack/users", wrapper.ListSlackUsers)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/ws/{workspaceId}/slack/users/{userId}", wrapper.GetSlackUserInfo)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/ws/{workspaceId}/sources", wrapper.ListSources)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/ws/{workspaceId}/sources", wrapper.CreateSource)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/api/v1/ws/{workspaceId}/sources/{sourceId}", wrapper.DeleteSource)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/api/v1/ws/{workspaceId}/sources/{sourceId}", wrapper.UpdateSource)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/ws/{workspaceId}/tickets", wrapper.ListTickets)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/ws/{workspaceId}/tickets", wrapper.CreateTicket)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/api/v1/ws/{workspaceId}/tickets/{ticketId}", wrapper.DeleteTicket)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/ws/{workspaceId}/tickets/{ticketId}", wrapper.GetTicket)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/api/v1/ws/{workspaceId}/tickets/{ticketId}", wrapper.UpdateTicket)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/ws/{workspaceId}/tickets/{ticketId}/comments", wrapper.ListComments)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/ws/{workspaceId}/tools", wrapper.ListToolSettings)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/api/v1/ws/{workspaceId}/tools/{providerId}", wrapper.SetToolEnabled)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+RbS28cNxL+K0TvHhzsaFpyjAWiPdmysxE2axse2XtIDIPqrplhxCbbJFuyIui/L/jo",
	"N9mP0ehhxBdrptnFqq+qviKLnJso4VnOGTAlo+ObKMcCZ6BAmE/vBc9ydZrqvwmLjqMcq220iBjOQH8q",
	"Hy8iAV8LIiCNjpUoYBHJZAsZ1u+p61yPlUoQtolubxfRGUkuICxVlY/nSf0fFxcyxwkEBV81RsyRfVs+",
	"NJic8CwDpgxYgucgFAHz4Jyn157XF1EiACtIX5p31lxkWEXHUYoVHCiSQbTov0JSryRJcXLxUYI4Tf0g",
	"1Eb9pmW031hYFZsKfa7m5ud/QKL0JCfm6YoXIoEP8LUA6TE2BZkIkivCmVfTXPBLkoLQD4EVmVaIcTP8",
	"s8feQtBxgyqZdnxYdxtgQd2xlGTDAE79II+ZtiZAUyOIKMjMH38XsI6Oo7/FdTLFLmTin/XwT5gWoF92",
	"0rAQ+Np4VGFVyIAmiigK47jYYT443jBF1PWv+ByonO9Dm4h308xIKMe3sfUpbMB6DWvCSKnWPJ0DiWMZ",
	"wPOAG1EzvfnOzu9xZ218Ndc55xRwY/SECc70QG8+G0OcpMbjIJbvcj+OCadczEEwA4VTrAxB4jQ17sH0",
	"fUOopdGeGgHog8YFTTlz6JV0ouCbDi1WZOeGEyRQPXwRZQVV5KD6WEjz2H7rPmjy7dFIbWwjZ3vImfT3",
	"Jewi+naw4QfuS/2fXBpBp6+bzw5IlnNhaUmXp+NoQ9S2OF8mPIuzg4z8WSjMSCy3kG9BpHF+sYlTnmHC",
	"YiPUYHfplOviWGpXjvCh+dbwsCX4vn12XICR7MOuJ3K8AQsqPscSvJCGGGMi9zcmXtQqhguBXbm8LNTW",
	"hnnbRsgwoXOIoqNNMFDttK9BOfndpGPKLR08VWeNC6pOBoYEMpPId5cgBEnBzzpFno4sP1hBKT7X7mnl",
	"cMNFVsSr6zH2asFuwlQQLblNsP3g6NDoJQjpaKtF+NEhutoCQ2oLCLJzSFNIkUMOEYkIQ2suElggoBLM",
	"MIoVSIWk4gJS5AQv6zUXYQo2IPyEVDqs1qgFd89rTYPD4bGiXHmDY002hSsebbO1W6zlWCEKWCrEGSDu",
	"FCnNQvCNSCUb1jXCICmk4hn50zq6O8Maa8DWXCBJuZJIbbFCWADKKU5gy2kKQiLO6LVf+rS63J5zpbQu",
	"iKTAFFkTEOgZLDdL9HukBMEb+D36YelbHFO9nvHOQoFtNKXe9Lz7yGkQiueTQghgqnLgMxfgjNfOtU5F",
	"16B+mBq3FqG2VzoRsGgGXDO+HYbh8D2DLNdZ9UYIL7eWX5fVgbBLTEn6Rbn3vOVBAJbe0OmYZ6VX48Na",
	"fqohn07CiXXHrjx6LwEz4u/acTVZ1ZrWJo0idcLZmpLEx0xWxKewTou+151eX5JSbN/rAdd2pvMpvqp2",
	"tWzN55T3UAnN8AY+irssCYYXsKHF1g6tAffKq+udNq+h/REv3xiK0tbCcf4m/6rdoZmAZ7tj09j/D3cw",
	"VmZT/Vobcud9D5EnlMvQji68rxQOlyl07TZ1Vrfy3cbUPhvPqs35rObGDgH3oP2QgBcE6D0TiNVgA0zv",
	"Ab++1XHYsI0w9c8XnrrpemMnW8wY0NOBhtvZVgBOz/xL150aODsUE29zz1pbt1cqZSqvND3enDUcUidm",
	"WeDJHBOLKzfDzAW9WyevwmB17Ou+sOjN77WAc6pHeJgWX2JCy7Wvb/1q5nvD9JBAssPQw5KcTkMBXK5v",
	"qk2ze+FLwWrdGpT3JSXSzreINljBl3PKk4sWG4z0SQ1sTdkdI2uLfFh+NLFypzZwz6fDzT8741+geduz",
	"vDq76Ns7r6E5a1FSzRpK+V3AajRvPYjRqhU9JKjVtq5whuma1AsAjw6qQ3NDglqU2EW3Uqsjs0G+zt4+",
	"+loWcYtXFynRynX80Mv3p40t2XF0uDxaHtpuNTCck+g4+nF5uPxRr4mw2ho4YpyT+PIo3gKmdgu8scsD",
	"7VCs/aHjNPo3qF/sCG2LzDlzuD4/POzsjnCeU5KYV+M/HHnVh2TtSLFQjAekG+fHo701fvcf/e3torLs",
	"Sgat+pVIVUWz3K9pV7XcqeFXp3Mv/Dp4NITviEl801gk3w75vdZq0Trm/c1vTD0kbh6t3n6+I7oTgfMb",
	"v4heHL7ot1HecoV+5gVLR+CJkyrrR1GqkvmpY1Wx070gZs/4h1PvvRvzqFi1s7ah9qSUbXRmx3K2FL2X",
	"hC3xjW/KyxSDOWzVvBvQi9Hh1bWPew3g1lnJvOj9yC4Yv2KouoBiXs8LD2grfAmPgppZv75yd0J2jOKh",
	"XmWwp3y2rQ8E7OGoOQhJMKUgEJHoShBF2GaJ/ltIheBrgSlyTbd/HKFnXKCjwS70vxBXWxBXRAJ6cfgT",
	"KjuHy2gRZYSRTG9wjkY71f3DFX9GtS/q3N57RJaNR09I6mBKZ0SlHvjT/ahXtWs9arohqOq9akWeP9+z",
	"Iu1zAI8ap7bxj6rG/2wqjLdEKi6uJ1SfX9zI74Ya25nuUmBuwapidaRmVeKnFq0ZxDvTpQLMWayBgEuP",
	"Tz/YAd8taSssNtA8LQnTs+LIwYHWgmdjBDpC+gyuesTPDdvbo3A3VYqcYQhLfw2YSeRtg78jOv9QAoIl",
	"wk34Jsc/4gK1zX86nD+cmaazHRfS3fQNsmvVcX9Sy/tK72ntoNZx4RhXWtl3JMrJ+6uGH+KbwpxsDO4A",
	"2rbclR09t6SL8rLw9AvS97lL6PjunpxgutwjieDGPKEsaKg9LQ+qk9vBBCjFTt/gLgKlvHmVfA/A7Vad",
	"hxDx3XWfVKWO9hfgzil9bK1ybhtx2A/vVzhFldJV2enImFoOrM/jG/uHI6EUKNjDtLZfX5vv9+FXPweV",
	"StyRhbyUgMrLepNYw3TYk20fgubx2NOCYP9Z4jsKfOC1XDhL9sH/9vhmmP/P3Ji9+PprAWavWjq7PuYe",
	"+ImT/93qlojn3ep8es+Fp4HXpMLjLquMFZ5S7D7XXsOl6az8gcpTLU3t0/AHLk2l20ZK0x4yL74pf/U3",
	"oe7sw2njnYHqV4rTCotVLZ0alKHl/ePbdvgA4TMjeYeq76OAdV/ldYdMf0qumpfkWoes/M1xsOSelIO+",
	"m3ToHt/URk6qk+Vvi8cKZSX4oboUinM6sjzinK5AKcI2T2qPXGk+baFSXSAcXasYufs5AzayTI/c3dsz",
	"RdB/nAkG6foK3943Hq3bgw+y9ehc3g/fsuz+YCB4e3EKeY5sDs2//wcAAP//FX7EMB5BAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
